# Project Name
TARGET = Main

# Sources 
# We told it to compile everything ending with .cpp, which was just a work-around and should be changed at some point
CPP_SOURCES = / SeedPlayground.cpp / ../../web-compiler/build_template/lib/DaisyDub/DspBlock.cpp

# Library Locations
LIBDAISY_DIR = ../../web-compiler/build_template/lib/libDaisy
DAISYSP_DIR = ../../web-compiler/build_template/lib/DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

