# Project Name
TARGET = Main

# Sources 
# We told it to compile everything ending with .cpp, which was just a work-around and should be changed at some point
CPP_SOURCES = $(wildcard *.cpp)

# Library Locations
LIBDAISY_DIR = lib/libDaisy
DAISYSP_DIR = lib/DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

